# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3f015e8ba83a53807dd87c739874d8971d094ab8579686bb44da58496b86bf05c1448b16100a6b8ab8e1adc3342c54fbd33cc23a7ce2e91748f382d442e3fa2

test:
  secret_key_base: 36da88fc1d7925aa65228eaeaee5abde81e0d7f1ca82a7eb413e0bf77792643952200fe6e33fac476ecbfdee1d2915d2375d6160ed287159057093c9074913da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
